export default {
  paletteName: 'http://clrs.cc/',
  cards: [
    { name: 'NAVY',    color: '#001F3F' },
    { name: 'BLUE',    color: '#0074D9' },
    { name: 'AQUA',    color: '#7FDBFF' },
    { name: 'TEAL',    color: '#39CCCC' },
    { name: 'OLIVE',   color: '#3D9970' },
    { name: 'GREEN',   color: '#2ECC40' },
    { name: 'LIME',    color: '#01FF70' },
    { name: 'YELLOW',  color: '#FFDC00' },
    { name: 'ORANGE',  color: '#FF851B' },
    { name: 'RED',     color: '#FF4136' },
    { name: 'MAROON',  color: '#85144B' },
    { name: 'FUCHSIA', color: '#F012BE' },
    { name: 'PURPLE',  color: '#B10DC9' },
    { name: 'BLACK',   color: '#111111' },
    { name: 'GRAY',    color: '#AAAAAA' },
    { name: 'SILVER',  color: '#DDDDDD' },
    { name: 'WHITE',   color: '#FFFFFF' },
  ],
  bgColor: '#222222',
  sortX: 'deg',
  sortY: 'saturationv',
}
