/*
console.log(
  JSON.stringify(JSON.parse(
    JSON.stringify(webcolor).toLowerCase()
  ), null, 2).replace(/"(\w+)": "(#\w+)",?/g, `$1: '$2',`)
)
*/
// http://htmlcolorcodes.com/color-names/
export const webcolor = [ // eslint-disable-line
  // Red HTML Color Names
  ['#CD5C5C', 'IndianRed'],
  ['#F08080', 'LightCoral'],
  ['#FA8072', 'Salmon'],
  ['#E9967A', 'DarkSalmon'],
  ['#FFA07A', 'LightSalmon'],
  ['#DC143C', 'Crimson'],
  ['#FF0000', 'Red'],
  ['#B22222', 'FireBrick'],
  ['#8B0000', 'DarkRed'],
  // Pink HTML Color Names
  ['#FFC0CB', 'Pink'],
  ['#FFB6C1', 'LightPink'],
  ['#FF69B4', 'HotPink'],
  ['#FF1493', 'DeepPink'],
  ['#C71585', 'MediumVioletRed'],
  ['#DB7093', 'PaleVioletRed'],
  // Orange HTML Color Names
  ['#FF7F50', 'Coral'],
  ['#FF6347', 'Tomato'],
  ['#FF4500', 'OrangeRed'],
  ['#FF8C00', 'DarkOrange'],
  ['#FFA500', 'Orange'],
  // Yellow HTML Color Names
  ['#FFD700', 'Gold'],
  ['#FFFF00', 'Yellow'],
  ['#FFFFE0', 'LightYellow'],
  ['#FFFACD', 'LemonChiffon'],
  ['#FAFAD2', 'LightGoldenrodYellow'],
  ['#FFEFD5', 'PapayaWhip'],
  ['#FFE4B5', 'Moccasin'],
  ['#FFDAB9', 'PeachPuff'],
  ['#EEE8AA', 'PaleGoldenrod'],
  ['#F0E68C', 'Khaki'],
  ['#BDB76B', 'DarkKhaki'],
  // Purple HTML Color Names
  ['#E6E6FA', 'Lavender'],
  ['#D8BFD8', 'Thistle'],
  ['#DDA0DD', 'Plum'],
  ['#EE82EE', 'Violet'],
  ['#DA70D6', 'Orchid'],
  ['#FF00FF', 'Fuchsia'],
  ['#FF00FF', 'Magenta'],
  ['#BA55D3', 'MediumOrchid'],
  ['#9370DB', 'MediumPurple'],
  ['#663399', 'RebeccaPurple'],
  ['#8A2BE2', 'BlueViolet'],
  ['#9400D3', 'DarkViolet'],
  ['#9932CC', 'DarkOrchid'],
  ['#8B008B', 'DarkMagenta'],
  ['#800080', 'Purple'],
  ['#4B0082', 'Indigo'],
  ['#6A5ACD', 'SlateBlue'],
  ['#483D8B', 'DarkSlateBlue'],
  ['#7B68EE', 'MediumSlateBlue'],
  // Green HTML Color Names
  ['#ADFF2F', 'GreenYellow'],
  ['#7FFF00', 'Chartreuse'],
  ['#7CFC00', 'LawnGreen'],
  ['#00FF00', 'Lime'],
  ['#32CD32', 'LimeGreen'],
  ['#98FB98', 'PaleGreen'],
  ['#90EE90', 'LightGreen'],
  ['#00FA9A', 'MediumSpringGreen'],
  ['#00FF7F', 'SpringGreen'],
  ['#3CB371', 'MediumSeaGreen'],
  ['#2E8B57', 'SeaGreen'],
  ['#228B22', 'ForestGreen'],
  ['#008000', 'Green'],
  ['#006400', 'DarkGreen'],
  ['#9ACD32', 'YellowGreen'],
  ['#6B8E23', 'OliveDrab'],
  ['#808000', 'Olive'],
  ['#556B2F', 'DarkOliveGreen'],
  ['#66CDAA', 'MediumAquamarine'],
  ['#8FBC8B', 'DarkSeaGreen'],
  ['#20B2AA', 'LightSeaGreen'],
  ['#008B8B', 'DarkCyan'],
  ['#008080', 'Teal'],
  // Blue HTML Color Names
  ['#00FFFF', 'Aqua'],
  ['#00FFFF', 'Cyan'],
  ['#E0FFFF', 'LightCyan'],
  ['#AFEEEE', 'PaleTurquoise'],
  ['#7FFFD4', 'Aquamarine'],
  ['#40E0D0', 'Turquoise'],
  ['#48D1CC', 'MediumTurquoise'],
  ['#00CED1', 'DarkTurquoise'],
  ['#5F9EA0', 'CadetBlue'],
  ['#4682B4', 'SteelBlue'],
  ['#B0C4DE', 'LightSteelBlue'],
  ['#B0E0E6', 'PowderBlue'],
  ['#ADD8E6', 'LightBlue'],
  ['#87CEEB', 'SkyBlue'],
  ['#87CEFA', 'LightSkyBlue'],
  ['#00BFFF', 'DeepSkyBlue'],
  ['#1E90FF', 'DodgerBlue'],
  ['#6495ED', 'CornflowerBlue'],
  ['#4169E1', 'RoyalBlue'],
  ['#0000FF', 'Blue'],
  ['#0000CD', 'MediumBlue'],
  ['#00008B', 'DarkBlue'],
  ['#000080', 'Navy'],
  ['#191970', 'MidnightBlue'],
  // Brown HTML Color Names
  ['#FFF8DC', 'Cornsilk'],
  ['#FFEBCD', 'BlanchedAlmond'],
  ['#FFE4C4', 'Bisque'],
  ['#FFDEAD', 'NavajoWhite'],
  ['#F5DEB3', 'Wheat'],
  ['#DEB887', 'BurlyWood'],
  ['#D2B48C', 'Tan'],
  ['#BC8F8F', 'RosyBrown'],
  ['#F4A460', 'SandyBrown'],
  ['#DAA520', 'Goldenrod'],
  ['#B8860B', 'DarkGoldenrod'],
  ['#CD853F', 'Peru'],
  ['#D2691E', 'Chocolate'],
  ['#8B4513', 'SaddleBrown'],
  ['#A0522D', 'Sienna'],
  ['#A52A2A', 'Brown'],
  ['#800000', 'Maroon'],
  // White HTML Color Names
  ['#FFFFFF', 'White'],
  ['#FFFAFA', 'Snow'],
  ['#F0FFF0', 'HoneyDew'],
  ['#F5FFFA', 'MintCream'],
  ['#F0FFFF', 'Azure'],
  ['#F0F8FF', 'AliceBlue'],
  ['#F8F8FF', 'GhostWhite'],
  ['#F5F5F5', 'WhiteSmoke'],
  ['#FFF5EE', 'SeaShell'],
  ['#F5F5DC', 'Beige'],
  ['#FDF5E6', 'OldLace'],
  ['#FFFAF0', 'FloralWhite'],
  ['#FFFFF0', 'Ivory'],
  ['#FAEBD7', 'AntiqueWhite'],
  ['#FAF0E6', 'Linen'],
  ['#FFF0F5', 'LavenderBlush'],
  ['#FFE4E1', 'MistyRose'],
  // Gray HTML Color Names
  ['#DCDCDC', 'Gainsboro'],
  ['#D3D3D3', 'LightGray'],
  ['#C0C0C0', 'Silver'],
  ['#A9A9A9', 'DarkGray'],
  ['#808080', 'Gray'],
  ['#696969', 'DimGray'],
  ['#778899', 'LightSlateGray'],
  ['#708090', 'SlateGray'],
  ['#2F4F4F', 'DarkSlateGray'],
  ['#000000', 'Black'],
]
